# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{enum_column}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephan Kaag"]
  s.date = %q{2009-10-14}
  s.description = %q{Ruby on Rails Enumerated Column Constraints}
  s.email = %q{stephan.kaag@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "LICENSE",
     "Rakefile",
     "VERSION",
     "lib/enum/active_record_helper.rb",
     "lib/enum/enum_adapter.rb",
     "lib/enum/mysql_adapter.rb",
     "lib/enum/postgresql_adapter.rb",
     "lib/enum/quoting.rb",
     "lib/enum/schema_definitions.rb",
     "lib/enum/schema_statements.rb",
     "lib/enum/sqlite3_adapter.rb",
     "lib/enum/validations.rb",
     "lib/enum_column.rb",
     "readme.html",
     "test/db/schema.rb",
     "test/enum_mysql_test.rb",
     "test/fixtures/db_definitions/mysql.drop.sql",
     "test/fixtures/db_definitions/mysql.sql",
     "test/fixtures/enumeration.rb",
     "test/mock_app/.gitignore",
     "test/mock_app/README",
     "test/mock_app/Rakefile",
     "test/mock_app/app/controllers/application_controller.rb",
     "test/mock_app/app/controllers/contents_controller.rb",
     "test/mock_app/app/models/content.rb",
     "test/mock_app/config/boot.rb",
     "test/mock_app/config/database.yml",
     "test/mock_app/config/environment.rb",
     "test/mock_app/config/environments/development.rb",
     "test/mock_app/config/environments/production.rb",
     "test/mock_app/config/environments/test.rb",
     "test/mock_app/config/initializers/backtrace_silencers.rb",
     "test/mock_app/config/initializers/inflections.rb",
     "test/mock_app/config/initializers/mime_types.rb",
     "test/mock_app/config/initializers/new_rails_defaults.rb",
     "test/mock_app/config/initializers/session_store.rb",
     "test/mock_app/config/locales/en.yml",
     "test/mock_app/config/routes.rb",
     "test/mock_app/config/sitemap.rb",
     "test/mock_app/db/migrate/20090826121911_create_contents.rb",
     "test/mock_app/db/schema.rb",
     "test/mock_app/db/test.sqlite3",
     "test/mock_app/public/index.html",
     "test/mock_app/script/console",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/stephankaag/enum_column}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby on Rails Enumerated Column Constraints}
  s.test_files = [
    "test/db/schema.rb",
     "test/enum_mysql_test.rb",
     "test/fixtures/enumeration.rb",
     "test/mock_app/app/controllers/application_controller.rb",
     "test/mock_app/app/controllers/contents_controller.rb",
     "test/mock_app/app/models/content.rb",
     "test/mock_app/config/boot.rb",
     "test/mock_app/config/environment.rb",
     "test/mock_app/config/environments/development.rb",
     "test/mock_app/config/environments/production.rb",
     "test/mock_app/config/environments/test.rb",
     "test/mock_app/config/initializers/backtrace_silencers.rb",
     "test/mock_app/config/initializers/inflections.rb",
     "test/mock_app/config/initializers/mime_types.rb",
     "test/mock_app/config/initializers/new_rails_defaults.rb",
     "test/mock_app/config/initializers/session_store.rb",
     "test/mock_app/config/routes.rb",
     "test/mock_app/config/sitemap.rb",
     "test/mock_app/db/migrate/20090826121911_create_contents.rb",
     "test/mock_app/db/schema.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
